---
collections:
  - name: ansible.posix
    version: '1.5.4'
    src: https://github.com/ansible-collections/ansible.posix.git
    scm: git
  - name: community.docker
    version: '3.8.1'
    src: https://github.com/ansible-collections/community.docker.git
    scm: git
  - name: community.general
    version: '8.5.0'
    src: https://github.com/ansible-collections/community.general.git
    scm: git
