---
- name: Update facts
  ansible.builtin.setup: ~
  tags:
    - fact

- name: Import Docker gpg key
  become: true
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - docker

- name: Add apt Docker repository
  become: true
  ansible.builtin.template:
    src: docker.repo.j2
    dest: /etc/apt/sources.list.d/docker.list
    backup: true
    mode: 0644
    owner: root
    group: root
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - docker

- name: Run apt update
  become: true
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"
  tags:
    - apt

- name: Stat docker-ce.repo file
  ansible.builtin.stat:
    path: "/etc/yum.repos.d/docker-ce.repo"
  register: docker_ce_repo

- name: Add Docker yum repo
  become: true
  ansible.builtin.command: "dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
  when: ansible_os_family == "RedHat" and not docker_ce_repo.stat.exists
  tags:
    - dnf

- name: Install docker
  become: true
  ansible.builtin.package:
    name: ['docker-ce', 'docker-ce-rootless-extras']
    state: present
  tags:
    - apt
    - dnf
    - docker
...
