---
- name: Add Docker systemd service
  become: true
  ansible.builtin.template:
    src: docker_rootful.service.j2
    dest: /etc/systemd/system/docker.service
    mode: 0644
    owner: root
    group: root
  tags:
    - docker
    - systemd

- name: Disable rootful Docker daemon
  become: true
  ansible.builtin.systemd:
    name: docker
    state: stopped
    enabled: false
  when: not docker_rootful_enabled
  tags:
    - docker
    - systemd

- name: Enable rootful Docker daemon
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
  when: docker_rootful_enabled
  tags:
    - docker
    - systemd

- name: Stat /run/user/{{ docker_user_info.uid }}/docker.sock
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.stat:
    path: "/run/user/{{ docker_user_info.uid }}/docker.sock"
  register: docker_rootless_sock
  tags:
    - docker

- name: Load the ip_tables module
  become: true
  community.general.modprobe:
    name: ip_tables
    state: present
  tags:
    - modprobe

- name: Install rootless docker
  become: true
  become_user: "{{ docker_user }}"
  environment:
    PATH: "{{ docker_user_info.home }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    XDG_RUNTIME_DIR: "/run/user/{{ docker_user_info.uid }}"
  ansible.builtin.command: dockerd-rootless-setuptool.sh install
  when: not docker_rootless_sock.stat.exists

- name: Enable and start Docker (rootful installation)
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.systemd:
    name: docker.service
    enabled: true
    state: started
    scope: user
    daemon_reload: true
  tags:
    - docker
    - systemd
...
