---
- name: Add user "{{ docker_user }}"
  become: true
  ansible.builtin.user:
    name: "{{ docker_user }}"
    state: present
    shell: /bin/bash
  register: docker_user_info
  tags:
    - user

- name: Adding user "{{ docker_user }}" to systemd-journal group
  become: true
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: systemd-journal
    append: true
  when: ansible_distribution == "Debian"
  tags:
    - user

- name: Ensure "{{ docker_user }}" is lingering
  ansible.builtin.stat:
    path: "/var/lib/systemd/linger/{{ docker_user }}"
  register: docker_user_lingering
  tags:
    - user
    - systemd

- name: Enable lingering for "{{ docker_user }}"
  become: true
  ansible.builtin.command: "loginctl enable-linger {{ docker_user }}"
  when: not docker_user_lingering.stat.exists
  tags:
    - user
    - systemd

- name: Create "{{ docker_user }}" ansible tmp dir
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.file:
    path: "{{ docker_user_info.home }}/.ansible/tmp"
    state: directory
    mode: "0700"
  tags:
    - user
...
