---
- name: Add Docker user
  become: true
  ansible.builtin.user:
    name: "{{ docker_user }}"
    state: present
    shell: /bin/bash
  register: docker_user_info

- name: Adding Docker user to systemd-journal group
  become: true
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: systemd-journal
    append: true
  when:
    - ansible_distribution == "Debian"

- name: Enable lingering for the Docker user
  become: true
  ansible.builtin.command:
    cmd: loginctl enable-linger {{ docker_user }}
    creates: /var/lib/systemd/linger/{{ docker_user }}
  register: enable_lingering
  changed_when: enable_lingering.rc != 0
  failed_when: enable_lingering.rc != 0

- name: Create Docker user Ansible tmp dir
  become: true
  become_user: "{{ docker_user }}"
  ansible.builtin.file:
    path: "{{ docker_user_info.home }}/.ansible/tmp"
    state: directory
    mode: "0700"
