---
- name: ensure we are using ubuntu
  fail:
    msg: "this role is ubuntu specific"
  when: not ansible_distribution == "Ubuntu"

- name: ensure we are using the x86_64 architecture
  fail:
    msg: "this role is currently x86_64 specific"
  when: not ansible_architecture == "x86_64"

- name: stat docker socket
  become: 'yes'
  stat:
    path: /var/run/docker.sock
  register: docker_socket
  tags:
    - docker
    - rootful

- name: fail if docker rootful is available
  fail:
    msg: "quitting since docker rootful is available"
  when: docker_socket.stat.exists
  tags:
    - docker
    - rootful
...
