---
- name: apt update
  become: 'yes'
  apt:
    update_cache: 'yes'
    cache_valid_time: 1800
  when: ansible_os_family == "Debian"
  tags:
    - apt

- name: install required packages
  become: 'yes'
  apt:
    name: ['acl', 'apt-transport-https', 'ca-certificates', 'curl', 'python3-pexpect', 'python3-pip', 'uidmap']
    state: present
    install_recommends: 'no'
  when: ansible_os_family == "Debian"
  tags:
    - acl
    - apt
    - packages
    - gidmap

- name: python3-rpm installation
  become: 'yes'
  dnf:
    name: "python3-rpm"
    state: present
  when: ansible_distribution == "RedHat"
  tags:
    - dnf
    - yum
    - packages
    - firewalld

- name: install python3 docker
  become: 'yes'
  pip:
    name: docker
    state: present
  tags:
    - docker
    - python

- name: sysctl net.ipv4.ip_forward
  become: 'yes'
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: 'yes'
    state: present
    reload: 'yes'
  tags:
    - sysctl

- name: sysctl kernel.unprivileged_userns_clone
  become: 'yes'
  sysctl:
    name: kernel.unprivileged_userns_clone
    value: "1"
    sysctl_set: 'yes'
    state: present
    reload: 'yes'
  when: ansible_distribution == "Debian"
  tags:
    - sysctl

- name: load the overlay2 module
  become: 'yes'
  modprobe:
    name: overlay
    state: present
    params: 'permit_mounts_in_userns=1'
  when: ansible_distribution == "Debian"
...
