---
- name: Converge
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Include Ansible role
      ansible.builtin.import_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
