---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
  provider_options:
    linked_clone: false
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  log: true
  inventory:
    host_vars:
      bullseye:
        docker_add_alias: true
        docker_allow_ping: true
        docker_allow_privileged_ports: false
        docker_rootful: false
        docker_user: bullseyeuser
        docker_user_bashrc: false
        docker_compose: false
      arctic:
        docker_add_alias: false
        docker_allow_ping: false
        docker_allow_privileged_ports: true
        docker_rootful: false
        docker_rootful_enabled: false
        docker_user: dockeruser
        docker_user_bashrc: true
        docker_compose: true
      emeraldroot:
        docker_add_alias: false
        docker_allow_ping: false
        docker_allow_privileged_ports: false
        docker_rootful: true
        docker_rootful_enabled: true
        docker_user: dockeruser
        docker_user_bashrc: false
        docker_compose: false
      focal:
        docker_add_alias: true
        docker_allow_ping: false
        docker_allow_privileged_ports: true
        docker_rootful: false
        docker_rootful_enabled: false
        docker_user: dockeruser
        docker_user_bashrc: false
        docker_compose: false
      focalroot:
        docker_add_alias: false
        docker_allow_ping: true
        docker_allow_privileged_ports: false
        docker_rootful: true
        docker_rootful_enabled: false
        docker_user: dockeruser
        docker_user_bashrc: false
        docker_compose: false
      jammy:
        docker_add_alias: false
        docker_allow_ping: false
        docker_allow_privileged_ports: false
        docker_rootful: false
        docker_rootful_enabled: false
        docker_user: jammyuser
        docker_user_bashrc: true
        docker_compose: true
platforms:
  - name: bullseye
    box: "debian/bullseye64"
    config_options:
      vm.boot_timeout: 600
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--natdnshostresolver1', 'on']"
    instance_raw_config_args:
      - 'vbguest.auto_update = false'
    memory: 1024
  - name: arctic
    box: "almalinux/8"
    config_options:
      vm.boot_timeout: 600
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--natdnshostresolver1', 'on']"
    instance_raw_config_args:
      - 'vbguest.auto_update = false'
    memory: 1024
  - name: focal
    box: "bento/ubuntu-20.04"
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: jammy
    box: "ubuntu/jammy64"
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]"
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: emeraldroot
    box: "almalinux/9"
    config_options:
      vm.boot_timeout: 600
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--natdnshostresolver1', 'on']"
    instance_raw_config_args:
      - 'vbguest.auto_update = false'
    memory: 1024
  - name: focalroot
    box: "bento/ubuntu-20.04"
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
