---
dependency:
  enabled: false
driver:
  name: vagrant
  provider:
    name: virtualbox
  provider_options:
    linked_clone: false
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  log: true
  inventory:
    host_vars:
      buster:
        add_alias: false
      bullseyeroot:
        docker_rootful: true
      centosroot:
        docker_rootful: true
      focalroot:
        docker_rootful: true
        docker_rootful_enabled: true
platforms:
  - name: buster
    box: bento/debian-10
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: bullseye
    box: debian/bullseye64
    instance_raw_config_args:
      - 'vbguest.auto_update = false'
    memory: 1024
  - name: bullseyeroot
    box: debian/bullseye64
    instance_raw_config_args:
      - 'vbguest.auto_update = false'
    memory: 1024
  - name: centos
    box: bento/centos-8
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: focal
    box: bento/ubuntu-20.04
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: centosroot
    box: bento/centos-8
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: focalroot
    box: bento/ubuntu-20.04
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: hirsute
    box: ubuntu/hirsute64
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]"
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint --exclude .git --exclude .github --exclude tests/
  yamllint -d "{extends: default, ignore: .git*, rules: {line-length: {max: 120, level: warning}}}" .
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
