---
dependency:
  name: galaxy
  enabled: true
driver:
  name: vagrant
  provider:
    name: virtualbox
  provider_options:
    linked_clone: false
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
  log: true
  inventory:
    host_vars:
      bullseye:
        docker_add_alias: true
        docker_allow_ping: true
        docker_allow_privileged_ports: false
        docker_rootful: false
        docker_user: bullseyeuser
      almalinux:
        docker_add_alias: false
        docker_allow_ping: true
        docker_allow_privileged_ports: false
        docker_rootful: false
        docker_rootful_enabled: false
        docker_user: dockeruser
      almalinuxroot:
        docker_add_alias: false
        docker_allow_ping: false
        docker_allow_privileged_ports: false
        docker_rootful: true
        docker_rootful_enabled: true
        docker_user: dockeruser
      focal:
        docker_add_alias: true
        docker_allow_ping: false
        docker_allow_privileged_ports: true
        docker_rootful: false
        docker_rootful_enabled: false
        docker_user: dockeruser
      focalroot:
        docker_add_alias: false
        docker_allow_ping: true
        docker_allow_privileged_ports: false
        docker_rootful: true
        docker_rootful_enabled: false
        docker_user: dockeruser
      jammy:
        docker_add_alias: false
        docker_allow_ping: false
        docker_allow_privileged_ports: false
        docker_rootful: false
        docker_rootful_enabled: false
        docker_user: jammyuser
platforms:
  - name: bullseye
    box: debian/bullseye64
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.auto_update = false'
    memory: 1024
  - name: almalinux
    box: almalinux/8
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.auto_update = false'
    memory: 1024
  - name: focal
    box: bento/ubuntu-20.04
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: jammy
    box: "jammy/20220317"
    box_url: "https://cloud-images.ubuntu.com/jammy/20220317/jammy-server-cloudimg-amd64-vagrant.box"
    box_download_checksum: "ed70e9a6a6bb53b00d07468c5f9b3818e2ec142e416369221a1ca14bb291893b"
    box_download_checksum_type: "sha256"
    config_options:
      vm.boot_timeout: 600
      synced_folder: false
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uart1', '0x3F8', '4']"
      - "customize ['modifyvm', :id, '--uartmode1', 'file', File::NULL]"
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
  - name: almalinuxroot
    box: almalinux/8
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.auto_update = false'
    memory: 1024
  - name: focalroot
    box: bento/ubuntu-20.04
    config_options:
      vm.boot_timeout: 600
    instance_raw_config_args:
      - 'vbguest.installer_options = { allow_kernel_upgrade: true }'
    memory: 1024
verifier:
  name: ansible
lint: |
  set -e
  ansible-lint
scenario:
  name: default
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
