---
- name: Verify
  hosts: all
  any_errors_fatal: true

  tasks:
    - name: register docker_user info
      become: 'yes'
      ansible.builtin.user:
        name: "{{ docker_user }}"
      check_mode: 'yes'
      register: docker_user_info

    - name: docker_user verification block
      block:
        - name: verify docker_user creation
          ansible.builtin.command: id "{{ docker_user }}"
          register: id_docker_user
          changed_when: id_docker_user.rc != 0
          failed_when: id_docker_user.rc != 0

        - name: verify docker_user subuid
          ansible.builtin.command: grep "^{{ docker_user }}:" /etc/subuid
          register: subuid_docker_user
          changed_when: subuid_docker_user.rc != 0
          failed_when: subuid_docker_user.rc != 0

        - name: verify docker_user subgid
          ansible.builtin.command: grep "^{{ docker_user }}:" /etc/subgid
          register: subgid_docker_user
          changed_when: subgid_docker_user.rc != 0
          failed_when: subgid_docker_user.rc != 0

        - name: verify docker_user dockerd
          ansible.builtin.shell: >
            set -o pipefail &&
            ps -fe | grep -E 'dockerd$|dockerd -s fuse-overlayfs$' | awk '{print $1}'
          args:
            executable: /bin/bash
          register: ps_dockerd
          changed_when: docker_user[:7] not in ps_dockerd.stdout
          failed_when: docker_user[:7] not in ps_dockerd.stdout

        - name: verify docker_rootless.sh
          ansible.builtin.stat:
            path: "{{ ansible_env.HOME }}/docker_rootless.sh"
          register: docker_rootless_sh
          changed_when: not docker_rootless_sh.stat.exists
          failed_when: not docker_rootless_sh.stat.exists
          when: docker_rootful or not docker_add_alias|bool

    - name: docker alias verification
      block:
        - name: stat {{ ansible_env.HOME }}/.bashrc
          ansible.builtin.stat:
            path: "{{ ansible_env.HOME }}/.bashrc"
          register: user_bashrc

        - name: check if .bash_aliases is used
          ansible.builtin.command: grep -q '.bash_aliases' "{{ ansible_env.HOME }}/.bashrc"
          register: check_aliases
          changed_when: check_aliases.rc >= 2
          failed_when: check_aliases.rc >= 2
          when: user_bashrc.stat.exists

        - name: verify rootless docker .bash_aliases alias
          ansible.builtin.command: grep -q "alias docker='sudo XDG_RUNTIME_DIR" "{{ ansible_env.HOME }}/.bash_aliases"
          register: verify_bash_aliases
          changed_when: verify_bash_aliases.rc != 0
          failed_when: verify_bash_aliases.rc != 0
          when: check_aliases.rc == 0 and user_bashrc.stat.exists and not docker_rootful

        - name: verify rootless docker .bashrc alias
          ansible.builtin.command: grep -q "alias docker='sudo XDG_RUNTIME_DIR" "{{ ansible_env.HOME }}/.bashrc"
          register: verify_bashrc_alias
          changed_when: verify_bashrc_alias.rc != 0
          failed_when: verify_bashrc_alias.rc != 0
          when: user_bashrc.stat.exists and check_aliases.rc != 0 and not docker_rootful
      when: docker_add_alias|bool and not docker_rootful

    - name: container verification block
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ docker_user_info.uid }}"
        PATH: "{{ docker_user_info.home }}/bin:{{ ansible_env.PATH }}"
        DOCKER_HOST: "unix:///run/user/{{ docker_user_info.uid }}/docker.sock"
      block:
        - name: reboot host
          become: 'yes'
          ansible.builtin.reboot:

        - name: wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
            delay: 10
            timeout: 120

        - name: start rootful nginx container
          become: 'yes'
          community.docker.docker_container:
            name: nginxroot
            image: konstruktoid/nginx
            state: started
            ports:
              - "8080:80"
            cap_drop: all
            capabilities:
              - chown
              - dac_override
              - net_bind_service
              - setgid
              - setuid
            pull: 'yes'
            hostname: "{{ ansible_nodename }}"
            container_default_behavior: compatibility
          when: docker_rootful|bool and docker_rootful_enabled|bool

        - name: verify running rootful container
          become: 'yes'
          community.docker.docker_container_info:
            name: nginxroot
          register: nginxroot_container_running
          changed_when: not nginxroot_container_running
          failed_when: not nginxroot_container_running
          when: docker_rootful|bool and docker_rootful_enabled|bool

        - name: assert rootful container settings
          ansible.builtin.assert:
            that:
              - docker_user_info.uid|string in nginxroot_container_running.container.NetworkSettings.SandboxKey
              - docker_user_info.home in nginxroot_container_running.container.HostnamePath
          when: docker_rootful|bool and docker_rootful_enabled|bool

        - name: start rootless nginx container
          become: 'yes'
          become_user: "{{ docker_user }}"
          community.docker.docker_container:
            name: nginx
            image: konstruktoid/nginx
            state: started
            cap_drop: all
            capabilities:
              - chown
              - dac_override
              - net_bind_service
              - setgid
              - setuid
            pull: 'yes'
            hostname: "{{ ansible_nodename }}"
            container_default_behavior: compatibility

        - name: verify running rootless container
          become: 'yes'
          become_user: "{{ docker_user }}"
          community.docker.docker_container_info:
            name: nginx
          register: nginx_container_running
          changed_when: not nginx_container_running
          failed_when: not nginx_container_running

        - name: assert rootless container settings
          ansible.builtin.assert:
            that:
              - docker_user_info.uid|string in nginx_container_running.container.NetworkSettings.SandboxKey
              - docker_user_info.home in nginx_container_running.container.HostnamePath

        - name: restart rootless nginx container
          become: 'yes'
          become_user: "{{ docker_user }}"
          community.docker.docker_container:
            name: nginx
            image: konstruktoid/nginx
            state: started
            restart: 'yes'
            ports:
              - "8081:80"
            cap_drop: all
            capabilities:
              - chown
              - dac_override
              - net_bind_service
              - setgid
              - setuid
            pull: 'yes'
            hostname: "{{ ansible_nodename }}"
            container_default_behavior: compatibility

        - name: verify restarted rootless container
          become: 'yes'
          become_user: "{{ docker_user }}"
          community.docker.docker_container_info:
            name: nginx
          register: nginx_container_restarted
          changed_when: not nginx_container_restarted
          failed_when: not nginx_container_restarted

        - name: assert rootless container settings
          ansible.builtin.assert:
            that:
              - docker_user_info.uid|string in nginx_container_restarted.container.NetworkSettings.SandboxKey
              - docker_user_info.home in nginx_container_restarted.container.HostnamePath

        - name: verify rootless port 80 nginx container
          become: 'yes'
          become_user: "{{ docker_user }}"
          community.docker.docker_container:
            name: nginxport
            image: konstruktoid/nginx
            state: started
            restart: 'yes'
            ports:
              - "80:80"
            cap_drop: all
            capabilities:
              - chown
              - dac_override
              - net_bind_service
              - setgid
              - setuid
            pull: 'yes'
            hostname: "{{ ansible_nodename }}"
            container_default_behavior: compatibility
          when: docker_allow_privileged_ports|bool

        - name: verify rootless port 80 container
          become: 'yes'
          become_user: "{{ docker_user }}"
          community.docker.docker_container_info:
            name: nginxport
          register: nginxport_container_restarted
          changed_when: not nginxport_container_restarted
          failed_when: not nginxport_container_restarted
          when: docker_allow_privileged_ports|bool

        - name: verify rootful website
          ansible.builtin.uri:
            url: http://127.0.0.1:8080
            return_content: 'yes'
          register: published
          failed_when: "'nginx' not in published.content"
          when: docker_rootful|bool and docker_rootful_enabled|bool

        - name: verify rootless website
          ansible.builtin.uri:
            url: http://127.0.0.1:8081
            return_content: 'yes'
          register: published
          failed_when: "'nginx' not in published.content"

        - name: verify port 80 website
          ansible.builtin.uri:
            url: http://127.0.0.1:80
            return_content: 'yes'
          register: published
          failed_when: "'nginx' not in published.content"
          when: docker_allow_privileged_ports|bool
...
