---
- name: Verify
  hosts: all
  any_errors_fatal: true

  tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions:
          - 'yml'

    - name: Include host vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/inventory/host_vars/{{ ansible_hostname }}"

    - name: Register docker_user info
      become: true
      ansible.builtin.user:
        name: "{{ docker_user }}"
      check_mode: true
      register: docker_user_info

    - name: User verification block
      block:
        - name: Verify docker_user creation
          ansible.builtin.command: id "{{ docker_user }}"
          register: id_docker_user
          changed_when: id_docker_user.rc != 0
          failed_when: id_docker_user.rc != 0

        - name: Verify docker_user subuid
          ansible.builtin.command: grep "^{{ docker_user }}:" /etc/subuid
          register: subuid_docker_user
          changed_when: subuid_docker_user.rc != 0
          failed_when: subuid_docker_user.rc != 0

        - name: Verify docker_user subgid
          ansible.builtin.command: grep "^{{ docker_user }}:" /etc/subgid
          register: subgid_docker_user
          changed_when: subgid_docker_user.rc != 0
          failed_when: subgid_docker_user.rc != 0

        - name: Verify docker_user dockerd
          ansible.builtin.shell: >
            set -o pipefail &&
            ps -fe | grep -E 'dockerd$|dockerd -s fuse-overlayfs$' | awk '{print $1}'
          args:
            executable: /bin/bash
          register: ps_dockerd
          changed_when: docker_user[:7] not in ps_dockerd.stdout
          failed_when: docker_user[:7] not in ps_dockerd.stdout

        - name: Verify docker_rootless.sh
          ansible.builtin.stat:
            path: "{{ ansible_env.HOME }}/docker_rootless.sh"
          register: docker_rootless_sh
          changed_when: not docker_rootless_sh.stat.exists
          failed_when: not docker_rootless_sh.stat.exists
          when: docker_rootful or not docker_add_alias | bool

        - name: Verify ping functionality
          ansible.builtin.command: ping -W1 -c1 1.1.1.1
          register: ping_allowed
          changed_when: false
          failed_when: ping_allowed.rc != 0
          when: docker_allow_ping | bool

    - name: Docker alias verification
      block:
        - name: Stat {{ ansible_env.HOME }}/.bashrc
          ansible.builtin.stat:
            path: "{{ ansible_env.HOME }}/.bashrc"
          register: user_bashrc

        - name: Check if .bash_aliases is used
          ansible.builtin.command: grep -q '.bash_aliases' "{{ ansible_env.HOME }}/.bashrc"
          register: check_aliases
          changed_when: check_aliases.rc >= 2
          failed_when: check_aliases.rc >= 2
          when: user_bashrc.stat.exists

        - name: Verify rootless docker .bash_aliases alias
          ansible.builtin.command: grep -q "alias docker='sudo XDG_RUNTIME_DIR" "{{ ansible_env.HOME }}/.bash_aliases"
          register: verify_bash_aliases
          changed_when: verify_bash_aliases.rc != 0
          failed_when: verify_bash_aliases.rc != 0
          when: check_aliases.rc == 0 and user_bashrc.stat.exists and not docker_rootful

        - name: Verify rootless docker .bashrc alias
          ansible.builtin.command: grep -q "alias docker='sudo XDG_RUNTIME_DIR" "{{ ansible_env.HOME }}/.bashrc"
          register: verify_bashrc_alias
          changed_when: verify_bashrc_alias.rc != 0
          failed_when: verify_bashrc_alias.rc != 0
          when: user_bashrc.stat.exists and check_aliases.rc != 0 and not docker_rootful
      when: docker_add_alias | bool and not docker_rootful

    - name: Docker bash completion verification
      block:
        - name: Stat "{{ docker_user_info.home }}/.bash_completion"
          become: true
          ansible.builtin.stat:
            path: "{{ docker_user_info.home }}/.bash_completion"
          register: bash_comp
          failed_when: not bash_comp.stat.exists

        - name: Stat {{ docker_user_info.home }}/.bash_completion.d/docker
          become: true
          ansible.builtin.stat:
            path: "{{ docker_user_info.home }}/.bash_completion.d/docker"
          register: bash_comp_docker
          failed_when: not bash_comp_docker.stat.exists
      when: docker_user_bashrc

    - name: Docker-compose verification
      block:
        - name: Stat {{ docker_user_info.home }}/.bash_completion.d/docker-compose
          become: true
          ansible.builtin.stat:
            path: "{{ docker_user_info.home }}/.bash_completion.d/docker-compose"
          register: bash_comp_docker_compose
          failed_when: not bash_comp_docker_compose.stat.exists
      when: docker_compose

    - name: Container verification block
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ docker_user_info.uid }}"
        PATH: "{{ docker_user_info.home }}/bin:{{ ansible_env.PATH }}"
        DOCKER_HOST: "unix:///run/user/{{ docker_user_info.uid }}/docker.sock"
      block:
        - name: Reboot host
          become: true
          ansible.builtin.reboot:

        - name: Wait for the host and reconnect
          ansible.builtin.wait_for:
            port: 22
            host: '{{ (ansible_ssh_host | default(ansible_host)) | default(inventory_hostname) }}'
            delay: 10
            timeout: 120

        - name: Test alpine ping container
          ansible.builtin.shell: >
            set -o pipefail &&
            "{{ ansible_env.HOME }}"/docker_rootless.sh run -ti konstruktoid/alpine ping -W1 -c1 1.1.1.1
          args:
            executable: /bin/bash
          register: alpine_ping
          changed_when: alpine_ping.stdout.find(' 0% packet loss') != -1
          failed_when: alpine_ping.stdout.find('  0% packet loss') != -1
          when: docker_allow_ping | bool and (docker_rootful or not docker_add_alias | bool)

        - name: Start rootful nginx container
          become: true
          community.docker.docker_container:
            name: nginxroot
            image: konstruktoid/nginx
            state: started
            ports:
              - "8080:80"
            cap_drop: all
            capabilities:
              - chown
              - dac_override
              - net_bind_service
              - setgid
              - setuid
            pull: true
            hostname: "{{ ansible_nodename }}"
            container_default_behavior: compatibility
          when: docker_rootful | bool and docker_rootful_enabled | bool

        - name: Verify running rootful container
          become: true
          community.docker.docker_container_info:
            name: nginxroot
          register: nginxroot_container_running
          changed_when: not nginxroot_container_running
          failed_when: not nginxroot_container_running
          when: docker_rootful | bool and docker_rootful_enabled | bool

        - name: Assert rootful container settings
          ansible.builtin.assert:
            that:
              - docker_user_info.uid|string in nginxroot_container_running.container.NetworkSettings.SandboxKey
              - docker_user_info.home in nginxroot_container_running.container.HostnamePath
          when: docker_rootful | bool and docker_rootful_enabled | bool

        - name: Start rootless nginx container
          become: true
          become_user: "{{ docker_user }}"
          community.docker.docker_container:
            name: nginx
            image: konstruktoid/nginx
            state: started
            cap_drop: all
            capabilities:
              - chown
              - dac_override
              - net_bind_service
              - setgid
              - setuid
            pull: true
            hostname: "{{ ansible_nodename }}"
            container_default_behavior: compatibility

        - name: Verify running rootless container
          become: true
          become_user: "{{ docker_user }}"
          community.docker.docker_container_info:
            name: nginx
          register: nginx_container_running
          changed_when: not nginx_container_running
          failed_when: not nginx_container_running

        - name: Assert rootless container settings
          ansible.builtin.assert:
            that:
              - docker_user_info.uid|string in nginx_container_running.container.NetworkSettings.SandboxKey
              - docker_user_info.home in nginx_container_running.container.HostnamePath

        - name: Restart rootless nginx container
          become: true
          become_user: "{{ docker_user }}"
          community.docker.docker_container:
            name: nginx
            image: konstruktoid/nginx
            state: started
            restart: true
            ports:
              - "8081:80"
            cap_drop: all
            capabilities:
              - chown
              - dac_override
              - net_bind_service
              - setgid
              - setuid
            pull: true
            hostname: "{{ ansible_nodename }}"
            container_default_behavior: compatibility

        - name: Verify restarted rootless container
          become: true
          become_user: "{{ docker_user }}"
          community.docker.docker_container_info:
            name: nginx
          register: nginx_container_restarted
          changed_when: not nginx_container_restarted
          failed_when: not nginx_container_restarted

        - name: Assert rootless container settings
          ansible.builtin.assert:
            that:
              - docker_user_info.uid|string in nginx_container_restarted.container.NetworkSettings.SandboxKey
              - docker_user_info.home in nginx_container_restarted.container.HostnamePath

        - name: Verify rootless port 80 nginx container
          become: true
          become_user: "{{ docker_user }}"
          community.docker.docker_container:
            name: nginxport
            image: konstruktoid/nginx
            state: started
            restart: true
            ports:
              - "80:80"
            cap_drop: all
            capabilities:
              - chown
              - dac_override
              - net_bind_service
              - setgid
              - setuid
            pull: true
            hostname: "{{ ansible_nodename }}"
            container_default_behavior: compatibility
          when: docker_allow_privileged_ports | bool

        - name: Verify rootless port 80 container
          become: true
          become_user: "{{ docker_user }}"
          community.docker.docker_container_info:
            name: nginxport
          register: nginxport_container_restarted
          changed_when: not nginxport_container_restarted
          failed_when: not nginxport_container_restarted
          when: docker_allow_privileged_ports | bool

        - name: Verify rootful website
          ansible.builtin.uri:
            url: http://127.0.0.1:8080
            return_content: true
          register: published
          failed_when: "'nginx' not in published.content"
          when: docker_rootful | bool and docker_rootful_enabled | bool

        - name: Verify rootless website
          ansible.builtin.uri:
            url: http://127.0.0.1:8081
            return_content: true
          register: published
          failed_when: "'nginx' not in published.content"

        - name: Verify port 80 website
          ansible.builtin.uri:
            url: http://127.0.0.1:80
            return_content: true
          register: published
          failed_when: "'nginx' not in published.content"
          when: docker_allow_privileged_ports | bool
...
