---
- name: Verify
  hosts: all
  any_errors_fatal: true

  tasks:
    - name: include default vars
      include_vars:
        dir: ../../defaults/
        extensions:
          - 'yml'

    - name: verify user creation
      command: id "{{ docker_user }}"
      register: id_docker_user
      changed_when: id_docker_user.rc != 0
      failed_when: id_docker_user.rc != 0

    - name: verify user subuid
      command: grep "^{{ docker_user }}:" /etc/subuid
      register: subuid_docker_user
      changed_when: subuid_docker_user.rc != 0
      failed_when: subuid_docker_user.rc != 0

    - name: verify user subgid
      command: grep "^{{ docker_user }}:" /etc/subgid
      register: subgid_docker_user
      changed_when: subgid_docker_user.rc != 0
      failed_when: subgid_docker_user.rc != 0

    - name: verify "{{ docker_user }}" dockerd
      shell: >
        set -o pipefail &&
        ps -fe | grep 'dockerd$' | awk '{print $1}'
      args:
        executable: /bin/bash
      register: ps_dockerd
      changed_when: docker_user[:7] not in ps_dockerd.stdout
      failed_when: docker_user[:7] not in ps_dockerd.stdout
...
